server:  
  type: default  
  applicationContextPath: / 
  adminContextPath: /
  maxThreads: 20480
  minThreads: 50
  gzip:
    bufferSize: 32KiB
  applicationConnectors:
  - type: http     
    port: 2017
    bindHost: 127.0.0.1 # only bind to loopback
    headerCacheSize: 512 bytes
    outputBufferSize: 64KiB
    maxRequestHeaderSize: 32KiB
    maxResponseHeaderSize: 32KiB
    inputBufferSize: 32KiB
    idleTimeout: 30 seconds
    minBufferPoolSize: 64 bytes
    bufferPoolIncrement: 1KiB
    maxBufferPoolSize: 64KiB
    acceptorThreads: 1
    selectorThreads: 2
    acceptQueueSize: 1024
    reuseAddress: true
    soLingerTime: 345s
    useServerHeader: false
    useDateHeader: true
    useForwardedHeaders: true
  adminConnectors:
  - type: http
    port: 2018

swagger:
  resourcePackage: com.project.micro.resources  
  
twitter.user: user
twitter.pass: sompass
twitter.accesstoken: 231313211c
twitter.accesstokensecret: 212112fUwBSz2F2HKZR34CI3b0TFn
twitter.consumersecret: 212tpwSXQJqlNEuvxlg
twitter.consumerkey: 454646546464646ZA